---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitcoind.fullname" . }}-rpc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
type: Opaque
stringData:
  rpcuser: {{ .Values.bitcoin.rpcUser | quote }}
  rpcpassword: {{ .Values.bitcoin.rpcPassword | default (randAlphaNum 32) | quote }}
