{{- if .Values.resourceQuota.enabled }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.namespace.name }}-quota
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cluster-addons.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requests.cpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requests.memory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limits.cpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limits.memory | quote }}
    pods: {{ .Values.resourceQuota.pods | quote }}
    persistentvolumeclaims: {{ .Values.resourceQuota.persistentVolumeClaims | quote }}
    requests.storage: {{ .Values.resourceQuota.storage | quote }}
{{- end }}
---
{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.namespace.name }}-limits
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cluster-addons.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.default.cpu }}
        memory: {{ .Values.limitRange.default.memory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu }}
        memory: {{ .Values.limitRange.defaultRequest.memory }}
      max:
        cpu: {{ .Values.limitRange.max.cpu }}
        memory: {{ .Values.limitRange.max.memory }}
{{- end }}
